// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UBookIt.Persistence;

#nullable disable

namespace UBookIt.Persistence.Migrations
{
    [DbContext(typeof(UBookItDbContext))]
    [Migration("20260911190750_AddResponsibility")]
    partial class AddResponsibility
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UBookIt.Persistence.Entities.BookingRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BookerEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTimeOffset?>("BookerErasedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("BookerName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("BookerPhone")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("EndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("MemberKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)")
                        .IsFixedLength();

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ServiceName")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("BookerEmail");

                    b.HasIndex("EndUtc")
                        .HasDatabaseName("IX_uBookItBooking_EndUtc_Unerased")
                        .HasFilter("[BookerErasedUtc] IS NULL");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("StartUtc", "EndUtc");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("StartUtc", "EndUtc"), new[] { "Status" });

                    b.ToTable("uBookItBooking", (string)null);
                });

            modelBuilder.Entity("UBookIt.Persistence.Entities.ClaimRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ResourceId"), new[] { "BookingId" });

                    b.HasIndex("BookingId", "ResourceId")
                        .IsUnique();

                    b.ToTable("uBookItResourceClaim", (string)null);
                });

            modelBuilder.Entity("UBookIt.Persistence.Entities.ExceptionRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId", "Date");

                    b.ToTable("uBookItResourceException", (string)null);
                });

            modelBuilder.Entity("UBookIt.Persistence.Entities.OpenHoursRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.ToTable("uBookItResourceOpenHours", (string)null);
                });

            modelBuilder.Entity("UBookIt.Persistence.Entities.ResourceCapabilityRow", b =>
                {
                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("ResourceId", "Key");

                    b.HasIndex("Key");

                    b.ToTable("uBookItResourceCapability", (string)null);
                });

            modelBuilder.Entity("UBookIt.Persistence.Entities.ResourceRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DirectlyBookable")
                        .HasColumnType("bit");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("GranularityMinutes")
                        .HasColumnType("int");

                    b.Property<int>("HorizonDays")
                        .HasColumnType("int");

                    b.Property<int>("LeadTimeMinutes")
                        .HasColumnType("int");

                    b.Property<int>("MaxDurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("MinDurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("uBookItResource", (string)null);
                });

            modelBuilder.Entity("UBookIt.Persistence.Entities.ResponsibilityRow", b =>
                {
                    b.Property<string>("SubjectType")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PartyType")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("PartyKey")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SubjectType", "SubjectId", "PartyType", "PartyKey");

                    b.HasIndex("SubjectType", "SubjectId");

                    b.ToTable("uBookItResponsibility", (string)null);
                });

            modelBuilder.Entity("UBookIt.Persistence.Entities.ServiceRoleCapabilityRow", b =>
                {
                    b.Property<long>("ServiceRoleId")
                        .HasColumnType("bigint");

                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("ServiceRoleId", "Key");

                    b.ToTable("uBookItServiceRoleCapability", (string)null);
                });

            modelBuilder.Entity("UBookIt.Persistence.Entities.ServiceRoleRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("VisitorSelectable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("uBookItServiceRole", (string)null);
                });

            modelBuilder.Entity("UBookIt.Persistence.Entities.ServiceRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DurationKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("MaxDurationMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("MinDurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.ToTable("uBookItService", (string)null);
                });

            modelBuilder.Entity("UBookIt.Persistence.Entities.ClaimRow", b =>
                {
                    b.HasOne("UBookIt.Persistence.Entities.BookingRow", null)
                        .WithMany("Claims")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UBookIt.Persistence.Entities.ResourceRow", null)
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("UBookIt.Persistence.Entities.ExceptionRow", b =>
                {
                    b.HasOne("UBookIt.Persistence.Entities.ResourceRow", null)
                        .WithMany("Exceptions")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UBookIt.Persistence.Entities.OpenHoursRow", b =>
                {
                    b.HasOne("UBookIt.Persistence.Entities.ResourceRow", null)
                        .WithMany("OpenHours")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UBookIt.Persistence.Entities.ResourceCapabilityRow", b =>
                {
                    b.HasOne("UBookIt.Persistence.Entities.ResourceRow", null)
                        .WithMany("Capabilities")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UBookIt.Persistence.Entities.ServiceRoleCapabilityRow", b =>
                {
                    b.HasOne("UBookIt.Persistence.Entities.ServiceRoleRow", null)
                        .WithMany("Capabilities")
                        .HasForeignKey("ServiceRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UBookIt.Persistence.Entities.ServiceRoleRow", b =>
                {
                    b.HasOne("UBookIt.Persistence.Entities.ServiceRow", null)
                        .WithMany("Roles")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UBookIt.Persistence.Entities.BookingRow", b =>
                {
                    b.Navigation("Claims");
                });

            modelBuilder.Entity("UBookIt.Persistence.Entities.ResourceRow", b =>
                {
                    b.Navigation("Capabilities");

                    b.Navigation("Exceptions");

                    b.Navigation("OpenHours");
                });

            modelBuilder.Entity("UBookIt.Persistence.Entities.ServiceRoleRow", b =>
                {
                    b.Navigation("Capabilities");
                });

            modelBuilder.Entity("UBookIt.Persistence.Entities.ServiceRow", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
