// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UBookIt.Persistence;

#nullable disable

namespace UBookIt.Persistence.Migrations
{
    [DbContext(typeof(UBookItDbContext))]
    [Migration("20260807125020_AddServices")]
    partial class AddServices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UBookIt.Persistence.Entities.BookingRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BookerEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("BookerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("BookerPhone")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("EndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("MemberKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("StartUtc", "EndUtc");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("StartUtc", "EndUtc"), new[] { "Status" });

                    b.ToTable("uBookItBooking", (string)null);
                });

            modelBuilder.Entity("UBookIt.Persistence.Entities.ClaimRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ResourceId"), new[] { "BookingId" });

                    b.HasIndex("BookingId", "ResourceId")
                        .IsUnique();

                    b.ToTable("uBookItResourceClaim", (string)null);
                });

            modelBuilder.Entity("UBookIt.Persistence.Entities.ExceptionRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId", "Date");

                    b.ToTable("uBookItResourceException", (string)null);
                });

            modelBuilder.Entity("UBookIt.Persistence.Entities.OpenHoursRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.ToTable("uBookItResourceOpenHours", (string)null);
                });

            modelBuilder.Entity("UBookIt.Persistence.Entities.ResourceRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("GranularityMinutes")
                        .HasColumnType("int");

                    b.Property<int>("HorizonDays")
                        .HasColumnType("int");

                    b.Property<int>("LeadTimeMinutes")
                        .HasColumnType("int");

                    b.Property<int>("MaxDurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("MinDurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("uBookItResource", (string)null);
                });

            modelBuilder.Entity("UBookIt.Persistence.Entities.ServiceRoleRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("uBookItServiceRole", (string)null);
                });

            modelBuilder.Entity("UBookIt.Persistence.Entities.ServiceRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DurationKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("MaxDurationMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("MinDurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.ToTable("uBookItService", (string)null);
                });

            modelBuilder.Entity("UBookIt.Persistence.Entities.ClaimRow", b =>
                {
                    b.HasOne("UBookIt.Persistence.Entities.BookingRow", null)
                        .WithMany("Claims")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UBookIt.Persistence.Entities.ResourceRow", null)
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("UBookIt.Persistence.Entities.ExceptionRow", b =>
                {
                    b.HasOne("UBookIt.Persistence.Entities.ResourceRow", null)
                        .WithMany("Exceptions")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UBookIt.Persistence.Entities.OpenHoursRow", b =>
                {
                    b.HasOne("UBookIt.Persistence.Entities.ResourceRow", null)
                        .WithMany("OpenHours")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UBookIt.Persistence.Entities.ServiceRoleRow", b =>
                {
                    b.HasOne("UBookIt.Persistence.Entities.ServiceRow", null)
                        .WithMany("Roles")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UBookIt.Persistence.Entities.BookingRow", b =>
                {
                    b.Navigation("Claims");
                });

            modelBuilder.Entity("UBookIt.Persistence.Entities.ResourceRow", b =>
                {
                    b.Navigation("Exceptions");

                    b.Navigation("OpenHours");
                });

            modelBuilder.Entity("UBookIt.Persistence.Entities.ServiceRow", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
