// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CancelBookingData, CancelBookingErrors, CancelBookingResponses, CreateResourceData, CreateResourceErrors, CreateResourceResponses, CreateServiceData, CreateServiceErrors, CreateServiceResponses, DeleteResourceData, DeleteResourceErrors, DeleteResourceResponses, DeleteServiceData, DeleteServiceErrors, DeleteServiceResponses, GetResourceData, GetResourceErrors, GetResourceResponses, GetServiceData, GetServiceErrors, GetServiceResponses, ListBookingsData, ListBookingsErrors, ListBookingsResponses, ListCapabilitiesData, ListCapabilitiesErrors, ListCapabilitiesResponses, ListResourcesData, ListResourcesErrors, ListResourcesResponses, ListResourceTypesData, ListResourceTypesErrors, ListResourceTypesResponses, ListServicesData, ListServicesErrors, ListServicesResponses, PreviewServiceConfigurationData, PreviewServiceConfigurationErrors, PreviewServiceConfigurationResponses, UpdateResourceData, UpdateResourceErrors, UpdateResourceResponses, UpdateServiceData, UpdateServiceErrors, UpdateServiceResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class UBookItBackofficeService {
    public static listBookings<ThrowOnError extends boolean = false>(options: Options<ListBookingsData, ThrowOnError>) {
        return (options.client ?? client).get<ListBookingsResponses, ListBookingsErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ubookitbackoffice/api/v1/bookings',
            ...options
        });
    }
    
    public static cancelBooking<ThrowOnError extends boolean = false>(options: Options<CancelBookingData, ThrowOnError>) {
        return (options.client ?? client).post<CancelBookingResponses, CancelBookingErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ubookitbackoffice/api/v1/bookings/{id}/cancel',
            ...options
        });
    }
    
    public static listResources<ThrowOnError extends boolean = false>(options?: Options<ListResourcesData, ThrowOnError>) {
        return (options?.client ?? client).get<ListResourcesResponses, ListResourcesErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ubookitbackoffice/api/v1/resources',
            ...options
        });
    }
    
    public static createResource<ThrowOnError extends boolean = false>(options?: Options<CreateResourceData, ThrowOnError>) {
        return (options?.client ?? client).post<CreateResourceResponses, CreateResourceErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ubookitbackoffice/api/v1/resources',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static deleteResource<ThrowOnError extends boolean = false>(options: Options<DeleteResourceData, ThrowOnError>) {
        return (options.client ?? client).delete<DeleteResourceResponses, DeleteResourceErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ubookitbackoffice/api/v1/resources/{id}',
            ...options
        });
    }
    
    public static getResource<ThrowOnError extends boolean = false>(options: Options<GetResourceData, ThrowOnError>) {
        return (options.client ?? client).get<GetResourceResponses, GetResourceErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ubookitbackoffice/api/v1/resources/{id}',
            ...options
        });
    }
    
    public static updateResource<ThrowOnError extends boolean = false>(options: Options<UpdateResourceData, ThrowOnError>) {
        return (options.client ?? client).put<UpdateResourceResponses, UpdateResourceErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ubookitbackoffice/api/v1/resources/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static listCapabilities<ThrowOnError extends boolean = false>(options?: Options<ListCapabilitiesData, ThrowOnError>) {
        return (options?.client ?? client).get<ListCapabilitiesResponses, ListCapabilitiesErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ubookitbackoffice/api/v1/resources/capabilities',
            ...options
        });
    }
    
    public static listResourceTypes<ThrowOnError extends boolean = false>(options?: Options<ListResourceTypesData, ThrowOnError>) {
        return (options?.client ?? client).get<ListResourceTypesResponses, ListResourceTypesErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ubookitbackoffice/api/v1/resources/types',
            ...options
        });
    }
    
    public static listServices<ThrowOnError extends boolean = false>(options?: Options<ListServicesData, ThrowOnError>) {
        return (options?.client ?? client).get<ListServicesResponses, ListServicesErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ubookitbackoffice/api/v1/services',
            ...options
        });
    }
    
    public static createService<ThrowOnError extends boolean = false>(options?: Options<CreateServiceData, ThrowOnError>) {
        return (options?.client ?? client).post<CreateServiceResponses, CreateServiceErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ubookitbackoffice/api/v1/services',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static deleteService<ThrowOnError extends boolean = false>(options: Options<DeleteServiceData, ThrowOnError>) {
        return (options.client ?? client).delete<DeleteServiceResponses, DeleteServiceErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ubookitbackoffice/api/v1/services/{id}',
            ...options
        });
    }
    
    public static getService<ThrowOnError extends boolean = false>(options: Options<GetServiceData, ThrowOnError>) {
        return (options.client ?? client).get<GetServiceResponses, GetServiceErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ubookitbackoffice/api/v1/services/{id}',
            ...options
        });
    }
    
    public static updateService<ThrowOnError extends boolean = false>(options: Options<UpdateServiceData, ThrowOnError>) {
        return (options.client ?? client).put<UpdateServiceResponses, UpdateServiceErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ubookitbackoffice/api/v1/services/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static previewServiceConfiguration<ThrowOnError extends boolean = false>(options?: Options<PreviewServiceConfigurationData, ThrowOnError>) {
        return (options?.client ?? client).post<PreviewServiceConfigurationResponses, PreviewServiceConfigurationErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ubookitbackoffice/api/v1/services/preview',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
}
