// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateResourceData, CreateResourceErrors, CreateResourceResponses, DeleteResourceData, DeleteResourceErrors, DeleteResourceResponses, GetResourceData, GetResourceErrors, GetResourceResponses, ListResourcesData, ListResourcesErrors, ListResourcesResponses, UpdateResourceData, UpdateResourceErrors, UpdateResourceResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class UBookItBackofficeService {
    public static listResources<ThrowOnError extends boolean = false>(options?: Options<ListResourcesData, ThrowOnError>) {
        return (options?.client ?? client).get<ListResourcesResponses, ListResourcesErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ubookitbackoffice/api/v1/resources',
            ...options
        });
    }
    
    public static createResource<ThrowOnError extends boolean = false>(options?: Options<CreateResourceData, ThrowOnError>) {
        return (options?.client ?? client).post<CreateResourceResponses, CreateResourceErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ubookitbackoffice/api/v1/resources',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static deleteResource<ThrowOnError extends boolean = false>(options: Options<DeleteResourceData, ThrowOnError>) {
        return (options.client ?? client).delete<DeleteResourceResponses, DeleteResourceErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ubookitbackoffice/api/v1/resources/{id}',
            ...options
        });
    }
    
    public static getResource<ThrowOnError extends boolean = false>(options: Options<GetResourceData, ThrowOnError>) {
        return (options.client ?? client).get<GetResourceResponses, GetResourceErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ubookitbackoffice/api/v1/resources/{id}',
            ...options
        });
    }
    
    public static updateResource<ThrowOnError extends boolean = false>(options: Options<UpdateResourceData, ThrowOnError>) {
        return (options.client ?? client).put<UpdateResourceResponses, UpdateResourceErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ubookitbackoffice/api/v1/resources/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
