// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44348' | (string & {});
};

export type AvailabilityExceptionModel = {
    date: string;
    windows: Array<TimeWindowModel>;
};

export type BookedResourceModel = {
    resourceId: string;
    displayName: string;
};

export type BookedServiceModel = {
    serviceId: string;
    displayName: string;
};

export type BookerContactModel = {
    name: string;
    email: string;
};

export type BookerModel = {
    condition: string;
    contact?: BookerContactModel | null;
    erasedUtc?: string | null;
};

export type BookingModel = {
    bookingId: string;
    reference: string;
    startUtc: string;
    endUtc: string;
    timeZoneId: string;
    status: string;
    createdUtc: string;
    booker: BookerModel;
    resources: Array<BookedResourceModel>;
    service?: BookedServiceModel | null;
};

export type CancelledBookingModel = {
    bookingId: string;
    status: string;
};

export type CapabilityUsageModel = {
    key: string;
    count: number;
};

export type ConfirmedBookingModel = {
    bookingId: string;
    status: string;
};

export type ConstraintsModel = {
    granularityMinutes: number;
    minDurationMinutes: number;
    maxDurationMinutes: number;
    leadTimeMinutes: number;
    horizonDays: number;
};

export type DayOfWeek = 'Sunday' | 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday';

export type DeclinedBookingModel = {
    bookingId: string;
    status: string;
};

export type DurationExclusionModel = {
    id: string;
    displayName: string;
    reason: string;
    boundMinutes: number;
};

export type ErasedBookerModel = {
    bookingId: string;
    erasedUtc: string;
};

export type FindBookingsByBookerModel = {
    email: string;
    skip?: number | null;
    take?: number | null;
};

export type MisalignedRoleModel = {
    resourceType: string;
    resourceId: string;
    displayName: string;
    windowStart: string;
    granularityMinutes: number;
};

export type MoveBookingRequestModel = {
    start: string;
    lengthMinutes: number;
};

export type MovedBookingModel = {
    bookingId: string;
    status: string;
    startUtc: string;
    endUtc: string;
    timeZoneId: string;
};

export type OpeningHoursModel = {
    day: DayOfWeek;
    start: string;
    end: string;
};

export type PagedBookingsModel = {
    total: number;
    items: Array<BookingModel>;
};

export type PagedResourcesModel = {
    total: number;
    items: Array<ResourceResponseModel>;
};

export type PagedServicesModel = {
    total: number;
    items: Array<ServiceResponseModel>;
};

export type PoolShortfallModel = {
    roles: Array<ShortfallRoleModel>;
    required: number;
    eligible: number;
};

export type PreviewResourceModel = {
    id: string;
    displayName: string;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown | string | null | string | null | number | null | string | null | string | null | undefined;
};

export type ResourceRequestModel = {
    type: string;
    displayName: string;
    description?: string | null;
    openingHours: Array<OpeningHoursModel>;
    exceptions: Array<AvailabilityExceptionModel>;
    capabilities: Array<string>;
    directlyBookable: boolean;
    constraints?: ConstraintsModel | null;
};

export type ResourceResponseModel = {
    id: string;
    type: string;
    displayName: string;
    description?: string | null;
    openingHours: Array<OpeningHoursModel>;
    exceptions: Array<AvailabilityExceptionModel>;
    capabilities: Array<string>;
    directlyBookable: boolean;
    constraints: ConstraintsModel;
};

export type ResourceTypeUsageModel = {
    type: string;
    count: number;
};

export type ResponsibilityAssignmentModel = {
    kind: string;
    key: string;
};

export type ResponsibilityPartyModel = {
    kind: string;
    key: string;
    exists: boolean;
    displayName?: string | null;
    userState?: string | null;
};

export type ResponsibilityRequestModel = {
    assignments: Array<ResponsibilityAssignmentModel>;
};

export type ResponsibilityResponseModel = {
    assignments: Array<ResponsibilityPartyModel>;
};

export type ServiceDurationModel = {
    kind: string;
    minutes?: number | null;
    minMinutes?: number | null;
    maxMinutes?: number | null;
};

export type ServicePreviewRequestModel = {
    roles: Array<ServicePreviewRoleModel>;
    duration?: ServiceDurationModel | null;
};

export type ServicePreviewResponseModel = {
    roles: Array<ServiceRoleChainModel>;
    startMisalignment?: StartMisalignmentModel | null;
    poolShortfall?: PoolShortfallModel | null;
};

export type ServicePreviewRoleModel = {
    resourceType: string;
    requiredCapabilities: Array<string>;
    count: number;
};

export type ServicePreviewStageModel = {
    total: number;
    items: Array<PreviewResourceModel>;
};

export type ServiceRequestModel = {
    name: string;
    duration?: ServiceDurationModel | null;
    roles: Array<ServiceRoleModel>;
};

export type ServiceResponseModel = {
    id: string;
    name: string;
    duration: ServiceDurationModel;
    roles: Array<ServiceRoleModel>;
};

export type ServiceRoleChainModel = {
    resourceType: string;
    requiredCapabilities: Array<string>;
    ofType: ServicePreviewStageModel;
    withCapabilities: ServicePreviewStageModel;
    canProvide: ServicePreviewStageModel;
    durationExclusions: Array<DurationExclusionModel>;
};

export type ServiceRoleModel = {
    resourceType: string;
    requiredCapabilities: Array<string>;
    count: number;
    visitorSelectable: boolean;
};

export type SettingResponseModel = {
    key: string;
    tier: string;
    valueKind: string;
    effectiveValue?: string | null;
    configuredValue?: string | null;
    isOverridden: boolean;
    isConfigured: boolean;
    requiresRestart: boolean;
};

export type SettingWriteModel = {
    value: string;
};

export type SettingsResponseModel = {
    settings: Array<SettingResponseModel>;
};

export type ShortfallRoleModel = {
    roleIndex: number;
    resourceType: string;
    requiredCapabilities: Array<string>;
    count: number;
};

export type StartMisalignmentModel = {
    first: MisalignedRoleModel;
    second: MisalignedRoleModel;
};

export type TimeWindowModel = {
    start: string;
    end: string;
};

export type ListBookingsData = {
    body?: never;
    path?: never;
    query: {
        from: string;
        to: string;
        statuses?: Array<string>;
        resourceIds?: Array<string>;
        skip?: number;
        take?: number;
    };
    url: '/umbraco/ubookitbackoffice/api/v1/bookings';
};

export type ListBookingsErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type ListBookingsResponses = {
    /**
     * OK
     */
    200: PagedBookingsModel;
};

export type ListBookingsResponse = ListBookingsResponses[keyof ListBookingsResponses];

export type CancelBookingData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/bookings/{id}/cancel';
};

export type CancelBookingErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type CancelBookingResponses = {
    /**
     * OK
     */
    200: CancelledBookingModel;
};

export type CancelBookingResponse = CancelBookingResponses[keyof CancelBookingResponses];

export type ConfirmBookingData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/bookings/{id}/confirm';
};

export type ConfirmBookingErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type ConfirmBookingResponses = {
    /**
     * OK
     */
    200: ConfirmedBookingModel;
};

export type ConfirmBookingResponse = ConfirmBookingResponses[keyof ConfirmBookingResponses];

export type DeclineBookingData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/bookings/{id}/decline';
};

export type DeclineBookingErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type DeclineBookingResponses = {
    /**
     * OK
     */
    200: DeclinedBookingModel;
};

export type DeclineBookingResponse = DeclineBookingResponses[keyof DeclineBookingResponses];

export type EraseBookerData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/bookings/{id}/erase-booker';
};

export type EraseBookerErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type EraseBookerResponses = {
    /**
     * OK
     */
    200: ErasedBookerModel;
};

export type EraseBookerResponse = EraseBookerResponses[keyof EraseBookerResponses];

export type MoveBookingData = {
    body?: MoveBookingRequestModel;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/bookings/{id}/move';
};

export type MoveBookingErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type MoveBookingResponses = {
    /**
     * OK
     */
    200: MovedBookingModel;
};

export type MoveBookingResponse = MoveBookingResponses[keyof MoveBookingResponses];

export type FindBookingsByBookerData = {
    body?: FindBookingsByBookerModel;
    path?: never;
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/bookings/find-by-booker';
};

export type FindBookingsByBookerErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type FindBookingsByBookerResponses = {
    /**
     * OK
     */
    200: PagedBookingsModel;
};

export type FindBookingsByBookerResponse = FindBookingsByBookerResponses[keyof FindBookingsByBookerResponses];

export type ListResourcesData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number;
        take?: number;
    };
    url: '/umbraco/ubookitbackoffice/api/v1/resources';
};

export type ListResourcesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type ListResourcesResponses = {
    /**
     * OK
     */
    200: PagedResourcesModel;
};

export type ListResourcesResponse = ListResourcesResponses[keyof ListResourcesResponses];

export type CreateResourceData = {
    body?: ResourceRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/resources';
};

export type CreateResourceErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type CreateResourceError = CreateResourceErrors[keyof CreateResourceErrors];

export type CreateResourceResponses = {
    /**
     * OK
     */
    200: ResourceResponseModel;
};

export type CreateResourceResponse = CreateResourceResponses[keyof CreateResourceResponses];

export type DeleteResourceData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/resources/{id}';
};

export type DeleteResourceErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type DeleteResourceError = DeleteResourceErrors[keyof DeleteResourceErrors];

export type DeleteResourceResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetResourceData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/resources/{id}';
};

export type GetResourceErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetResourceError = GetResourceErrors[keyof GetResourceErrors];

export type GetResourceResponses = {
    /**
     * OK
     */
    200: ResourceResponseModel;
};

export type GetResourceResponse = GetResourceResponses[keyof GetResourceResponses];

export type UpdateResourceData = {
    body?: ResourceRequestModel;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/resources/{id}';
};

export type UpdateResourceErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type UpdateResourceError = UpdateResourceErrors[keyof UpdateResourceErrors];

export type UpdateResourceResponses = {
    /**
     * OK
     */
    200: ResourceResponseModel;
};

export type UpdateResourceResponse = UpdateResourceResponses[keyof UpdateResourceResponses];

export type GetResourceResponsibilityData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/resources/{id}/responsibility';
};

export type GetResourceResponsibilityErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetResourceResponsibilityResponses = {
    /**
     * OK
     */
    200: ResponsibilityResponseModel;
};

export type GetResourceResponsibilityResponse = GetResourceResponsibilityResponses[keyof GetResourceResponsibilityResponses];

export type PutResourceResponsibilityData = {
    body?: ResponsibilityRequestModel;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/resources/{id}/responsibility';
};

export type PutResourceResponsibilityErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutResourceResponsibilityError = PutResourceResponsibilityErrors[keyof PutResourceResponsibilityErrors];

export type PutResourceResponsibilityResponses = {
    /**
     * OK
     */
    200: ResponsibilityResponseModel;
};

export type PutResourceResponsibilityResponse = PutResourceResponsibilityResponses[keyof PutResourceResponsibilityResponses];

export type ListCapabilitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/resources/capabilities';
};

export type ListCapabilitiesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type ListCapabilitiesResponses = {
    /**
     * OK
     */
    200: Array<CapabilityUsageModel>;
};

export type ListCapabilitiesResponse = ListCapabilitiesResponses[keyof ListCapabilitiesResponses];

export type ListResourceTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/resources/types';
};

export type ListResourceTypesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type ListResourceTypesResponses = {
    /**
     * OK
     */
    200: Array<ResourceTypeUsageModel>;
};

export type ListResourceTypesResponse = ListResourceTypesResponses[keyof ListResourceTypesResponses];

export type ListServicesData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number;
        take?: number;
    };
    url: '/umbraco/ubookitbackoffice/api/v1/services';
};

export type ListServicesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type ListServicesResponses = {
    /**
     * OK
     */
    200: PagedServicesModel;
};

export type ListServicesResponse = ListServicesResponses[keyof ListServicesResponses];

export type CreateServiceData = {
    body?: ServiceRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/services';
};

export type CreateServiceErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type CreateServiceError = CreateServiceErrors[keyof CreateServiceErrors];

export type CreateServiceResponses = {
    /**
     * OK
     */
    200: ServiceResponseModel;
};

export type CreateServiceResponse = CreateServiceResponses[keyof CreateServiceResponses];

export type DeleteServiceData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/services/{id}';
};

export type DeleteServiceErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteServiceError = DeleteServiceErrors[keyof DeleteServiceErrors];

export type DeleteServiceResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetServiceData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/services/{id}';
};

export type GetServiceErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetServiceError = GetServiceErrors[keyof GetServiceErrors];

export type GetServiceResponses = {
    /**
     * OK
     */
    200: ServiceResponseModel;
};

export type GetServiceResponse = GetServiceResponses[keyof GetServiceResponses];

export type UpdateServiceData = {
    body?: ServiceRequestModel;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/services/{id}';
};

export type UpdateServiceErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type UpdateServiceError = UpdateServiceErrors[keyof UpdateServiceErrors];

export type UpdateServiceResponses = {
    /**
     * OK
     */
    200: ServiceResponseModel;
};

export type UpdateServiceResponse = UpdateServiceResponses[keyof UpdateServiceResponses];

export type GetServiceResponsibilityData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/services/{id}/responsibility';
};

export type GetServiceResponsibilityErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetServiceResponsibilityResponses = {
    /**
     * OK
     */
    200: ResponsibilityResponseModel;
};

export type GetServiceResponsibilityResponse = GetServiceResponsibilityResponses[keyof GetServiceResponsibilityResponses];

export type PutServiceResponsibilityData = {
    body?: ResponsibilityRequestModel;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/services/{id}/responsibility';
};

export type PutServiceResponsibilityErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutServiceResponsibilityError = PutServiceResponsibilityErrors[keyof PutServiceResponsibilityErrors];

export type PutServiceResponsibilityResponses = {
    /**
     * OK
     */
    200: ResponsibilityResponseModel;
};

export type PutServiceResponsibilityResponse = PutServiceResponsibilityResponses[keyof PutServiceResponsibilityResponses];

export type PreviewServiceConfigurationData = {
    body?: ServicePreviewRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/services/preview';
};

export type PreviewServiceConfigurationErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PreviewServiceConfigurationError = PreviewServiceConfigurationErrors[keyof PreviewServiceConfigurationErrors];

export type PreviewServiceConfigurationResponses = {
    /**
     * OK
     */
    200: ServicePreviewResponseModel;
};

export type PreviewServiceConfigurationResponse = PreviewServiceConfigurationResponses[keyof PreviewServiceConfigurationResponses];

export type GetSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/settings';
};

export type GetSettingsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetSettingsResponses = {
    /**
     * OK
     */
    200: SettingsResponseModel;
};

export type GetSettingsResponse = GetSettingsResponses[keyof GetSettingsResponses];

export type ResetSettingData = {
    body?: never;
    path: {
        key: string;
    };
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/settings/{key}';
};

export type ResetSettingErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type ResetSettingError = ResetSettingErrors[keyof ResetSettingErrors];

export type ResetSettingResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutSettingData = {
    body?: SettingWriteModel;
    path: {
        key: string;
    };
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/settings/{key}';
};

export type PutSettingErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutSettingError = PutSettingErrors[keyof PutSettingErrors];

export type PutSettingResponses = {
    /**
     * OK
     */
    200: unknown;
};
