// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44348' | (string & {});
};

export type AvailabilityExceptionModel = {
    date: string;
    windows: Array<TimeWindowModel>;
};

export type ConstraintsModel = {
    granularityMinutes: number;
    minDurationMinutes: number;
    maxDurationMinutes: number;
    leadTimeMinutes: number;
    horizonDays: number;
};

export type DayOfWeek = 'Sunday' | 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday';

export type OpeningHoursModel = {
    day: DayOfWeek;
    start: string;
    end: string;
};

export type PagedResourcesModel = {
    total: number;
    items: Array<ResourceResponseModel>;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown | string | null | string | null | number | null | string | null | string | null | undefined;
};

export type ResourceRequestModel = {
    type: string;
    displayName: string;
    description?: string | null;
    openingHours: Array<OpeningHoursModel>;
    exceptions: Array<AvailabilityExceptionModel>;
    constraints?: ConstraintsModel | null;
};

export type ResourceResponseModel = {
    id: string;
    type: string;
    displayName: string;
    description?: string | null;
    openingHours: Array<OpeningHoursModel>;
    exceptions: Array<AvailabilityExceptionModel>;
    constraints: ConstraintsModel;
};

export type TimeWindowModel = {
    start: string;
    end: string;
};

export type ListResourcesData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number;
        take?: number;
    };
    url: '/umbraco/ubookitbackoffice/api/v1/resources';
};

export type ListResourcesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type ListResourcesResponses = {
    /**
     * OK
     */
    200: PagedResourcesModel;
};

export type ListResourcesResponse = ListResourcesResponses[keyof ListResourcesResponses];

export type CreateResourceData = {
    body?: ResourceRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/resources';
};

export type CreateResourceErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type CreateResourceError = CreateResourceErrors[keyof CreateResourceErrors];

export type CreateResourceResponses = {
    /**
     * OK
     */
    200: ResourceResponseModel;
};

export type CreateResourceResponse = CreateResourceResponses[keyof CreateResourceResponses];

export type DeleteResourceData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/resources/{id}';
};

export type DeleteResourceErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type DeleteResourceError = DeleteResourceErrors[keyof DeleteResourceErrors];

export type DeleteResourceResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetResourceData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/resources/{id}';
};

export type GetResourceErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetResourceError = GetResourceErrors[keyof GetResourceErrors];

export type GetResourceResponses = {
    /**
     * OK
     */
    200: ResourceResponseModel;
};

export type GetResourceResponse = GetResourceResponses[keyof GetResourceResponses];

export type UpdateResourceData = {
    body?: ResourceRequestModel;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/resources/{id}';
};

export type UpdateResourceErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type UpdateResourceError = UpdateResourceErrors[keyof UpdateResourceErrors];

export type UpdateResourceResponses = {
    /**
     * OK
     */
    200: ResourceResponseModel;
};

export type UpdateResourceResponse = UpdateResourceResponses[keyof UpdateResourceResponses];
