// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44348' | (string & {});
};

export type AvailabilityExceptionModel = {
    date: string;
    windows: Array<TimeWindowModel>;
};

export type CapabilityUsageModel = {
    key: string;
    count: number;
};

export type ConstraintsModel = {
    granularityMinutes: number;
    minDurationMinutes: number;
    maxDurationMinutes: number;
    leadTimeMinutes: number;
    horizonDays: number;
};

export type DayOfWeek = 'Sunday' | 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday';

export type DurationExclusionModel = {
    id: string;
    displayName: string;
    reason: string;
    boundMinutes: number;
};

export type OpeningHoursModel = {
    day: DayOfWeek;
    start: string;
    end: string;
};

export type PagedResourcesModel = {
    total: number;
    items: Array<ResourceResponseModel>;
};

export type PagedServicesModel = {
    total: number;
    items: Array<ServiceResponseModel>;
};

export type PreviewResourceModel = {
    id: string;
    displayName: string;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown | string | null | string | null | number | null | string | null | string | null | undefined;
};

export type ResourceRequestModel = {
    type: string;
    displayName: string;
    description?: string | null;
    openingHours: Array<OpeningHoursModel>;
    exceptions: Array<AvailabilityExceptionModel>;
    capabilities: Array<string>;
    constraints?: ConstraintsModel | null;
};

export type ResourceResponseModel = {
    id: string;
    type: string;
    displayName: string;
    description?: string | null;
    openingHours: Array<OpeningHoursModel>;
    exceptions: Array<AvailabilityExceptionModel>;
    capabilities: Array<string>;
    constraints: ConstraintsModel;
};

export type ResourceTypeUsageModel = {
    type: string;
    count: number;
};

export type ServiceDurationModel = {
    kind: string;
    minutes?: number | null;
    minMinutes?: number | null;
    maxMinutes?: number | null;
};

export type ServicePreviewRequestModel = {
    roles: Array<ServicePreviewRoleModel>;
    duration?: ServiceDurationModel | null;
};

export type ServicePreviewResponseModel = {
    roles: Array<ServiceRoleChainModel>;
};

export type ServicePreviewRoleModel = {
    resourceType: string;
    requiredCapabilities: Array<string>;
};

export type ServicePreviewStageModel = {
    total: number;
    items: Array<PreviewResourceModel>;
};

export type ServiceRequestModel = {
    name: string;
    duration?: ServiceDurationModel | null;
    roles: Array<ServiceRoleModel>;
};

export type ServiceResponseModel = {
    id: string;
    name: string;
    duration: ServiceDurationModel;
    roles: Array<ServiceRoleModel>;
};

export type ServiceRoleChainModel = {
    resourceType: string;
    requiredCapabilities: Array<string>;
    ofType: ServicePreviewStageModel;
    withCapabilities: ServicePreviewStageModel;
    canProvide: ServicePreviewStageModel;
    durationExclusions: Array<DurationExclusionModel>;
};

export type ServiceRoleModel = {
    resourceType: string;
    requiredCapabilities: Array<string>;
    count: number;
};

export type TimeWindowModel = {
    start: string;
    end: string;
};

export type ListResourcesData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number;
        take?: number;
    };
    url: '/umbraco/ubookitbackoffice/api/v1/resources';
};

export type ListResourcesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type ListResourcesResponses = {
    /**
     * OK
     */
    200: PagedResourcesModel;
};

export type ListResourcesResponse = ListResourcesResponses[keyof ListResourcesResponses];

export type CreateResourceData = {
    body?: ResourceRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/resources';
};

export type CreateResourceErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type CreateResourceError = CreateResourceErrors[keyof CreateResourceErrors];

export type CreateResourceResponses = {
    /**
     * OK
     */
    200: ResourceResponseModel;
};

export type CreateResourceResponse = CreateResourceResponses[keyof CreateResourceResponses];

export type DeleteResourceData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/resources/{id}';
};

export type DeleteResourceErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type DeleteResourceError = DeleteResourceErrors[keyof DeleteResourceErrors];

export type DeleteResourceResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetResourceData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/resources/{id}';
};

export type GetResourceErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetResourceError = GetResourceErrors[keyof GetResourceErrors];

export type GetResourceResponses = {
    /**
     * OK
     */
    200: ResourceResponseModel;
};

export type GetResourceResponse = GetResourceResponses[keyof GetResourceResponses];

export type UpdateResourceData = {
    body?: ResourceRequestModel;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/resources/{id}';
};

export type UpdateResourceErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type UpdateResourceError = UpdateResourceErrors[keyof UpdateResourceErrors];

export type UpdateResourceResponses = {
    /**
     * OK
     */
    200: ResourceResponseModel;
};

export type UpdateResourceResponse = UpdateResourceResponses[keyof UpdateResourceResponses];

export type ListCapabilitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/resources/capabilities';
};

export type ListCapabilitiesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type ListCapabilitiesResponses = {
    /**
     * OK
     */
    200: Array<CapabilityUsageModel>;
};

export type ListCapabilitiesResponse = ListCapabilitiesResponses[keyof ListCapabilitiesResponses];

export type ListResourceTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/resources/types';
};

export type ListResourceTypesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type ListResourceTypesResponses = {
    /**
     * OK
     */
    200: Array<ResourceTypeUsageModel>;
};

export type ListResourceTypesResponse = ListResourceTypesResponses[keyof ListResourceTypesResponses];

export type ListServicesData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number;
        take?: number;
    };
    url: '/umbraco/ubookitbackoffice/api/v1/services';
};

export type ListServicesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type ListServicesResponses = {
    /**
     * OK
     */
    200: PagedServicesModel;
};

export type ListServicesResponse = ListServicesResponses[keyof ListServicesResponses];

export type CreateServiceData = {
    body?: ServiceRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/services';
};

export type CreateServiceErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type CreateServiceError = CreateServiceErrors[keyof CreateServiceErrors];

export type CreateServiceResponses = {
    /**
     * OK
     */
    200: ServiceResponseModel;
};

export type CreateServiceResponse = CreateServiceResponses[keyof CreateServiceResponses];

export type DeleteServiceData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/services/{id}';
};

export type DeleteServiceErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteServiceError = DeleteServiceErrors[keyof DeleteServiceErrors];

export type DeleteServiceResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetServiceData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/services/{id}';
};

export type GetServiceErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetServiceError = GetServiceErrors[keyof GetServiceErrors];

export type GetServiceResponses = {
    /**
     * OK
     */
    200: ServiceResponseModel;
};

export type GetServiceResponse = GetServiceResponses[keyof GetServiceResponses];

export type UpdateServiceData = {
    body?: ServiceRequestModel;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/services/{id}';
};

export type UpdateServiceErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type UpdateServiceError = UpdateServiceErrors[keyof UpdateServiceErrors];

export type UpdateServiceResponses = {
    /**
     * OK
     */
    200: ServiceResponseModel;
};

export type UpdateServiceResponse = UpdateServiceResponses[keyof UpdateServiceResponses];

export type PreviewServiceConfigurationData = {
    body?: ServicePreviewRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ubookitbackoffice/api/v1/services/preview';
};

export type PreviewServiceConfigurationErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PreviewServiceConfigurationError = PreviewServiceConfigurationErrors[keyof PreviewServiceConfigurationErrors];

export type PreviewServiceConfigurationResponses = {
    /**
     * OK
     */
    200: ServicePreviewResponseModel;
};

export type PreviewServiceConfigurationResponse = PreviewServiceConfigurationResponses[keyof PreviewServiceConfigurationResponses];
