export default {
  ubookitSection: {
    label: "uBookIt",
  },
  ubookitResources: {
    label: "Resources",
    create: "Create resource",
    edit: "Edit",
    delete: "Delete",
    empty: "No resources yet. Create the first one to start taking bookings.",
    name: "Name",
    type: "Type",
    typeKey: "Type key",
    description: "Description",
    availability: "Availability",
    details: "Details",
    openingHours: "Opening hours",
    exceptions: "Exceptions",
    exception: "Exception",
    constraints: "Constraints",
    save: "Save",
    cancel: "Cancel",
    back: "Back to resources",
    newResource: "New resource",
    addWindow: "Add window",
    removeWindow: "Remove window",
    addException: "Add exception",
    removeException: "Remove exception",
    closedAllDay: "Closed all day",
    from: "From",
    to: "To",
    date: "Date",
    granularity: "Slot granularity (minutes)",
    minDuration: "Minimum duration (minutes)",
    maxDuration: "Maximum duration (minutes)",
    leadTime: "Minimum notice (minutes)",
    horizon: "Booking horizon (days)",
    previousPage: "Previous page",
    nextPage: "Next page",
    showing: "Showing %0%–%1% of %2%",
    actions: "Actions",
    tableLabel: "Bookable resources",
    pagingLabel: "Resource list pages",
    loadingList: "Loading resources",
    loadingResource: "Loading resource",
    errorSummary: "The resource could not be saved:",
    exceptionNeedsDate: "Each exception needs a date before saving.",
    dayMonday: "Monday",
    dayTuesday: "Tuesday",
    dayWednesday: "Wednesday",
    dayThursday: "Thursday",
    dayFriday: "Friday",
    daySaturday: "Saturday",
    daySunday: "Sunday",
    listLoadFailed: "The resource list could not be loaded.",
    resourceLoadFailed: "The resource could not be loaded.",
    resourceSaveFailed: "The resource could not be saved.",
    confirmDeleteHeadline: "Delete resource",
    confirmDeleteContent: "Delete %0%? This cannot be undone.",
    confirmDelete: "Delete",
    confirmFailed: "The confirmation dialog could not be shown, so nothing was deleted.",
  },
  ubookitServices: {
    label: "Services",
    create: "Create service",
    edit: "Edit",
    delete: "Delete",
    empty: "No services yet. Create one to offer a bookable service.",
    name: "Name",
    requirements: "Service Requirements",
    requirementsSummary: "Requires",
    requirementEntry: "%0% × %1%",
    requirementNone: "—",
    details: "Details",
    duration: "Duration",
    durationInherit: "Use each resource's minimum duration",
    durationInheritHint:
      "The booking length comes from whichever resource is booked, using its minimum duration.",
    durationFixed: "Fixed duration",
    durationMinutes: "Minutes",
    durationInheritSummary: "Resource minimum",
    durationFixedSummary: "%0% minutes",
    resourceType: "Resource type",
    resourceTypeHint: "Choose a type already in use, or enter a new one.",
    resourceTypeUnknown: "No resources currently have this type.",
    save: "Save",
    cancel: "Cancel",
    back: "Back to services",
    newService: "New service",
    previousPage: "Previous page",
    nextPage: "Next page",
    showing: "Showing %0%–%1% of %2%",
    actions: "Actions",
    tableLabel: "Bookable services",
    pagingLabel: "Service list pages",
    loadingList: "Loading services",
    loadingService: "Loading service",
    errorSummary: "The service could not be saved:",
    listLoadFailed: "The service list could not be loaded.",
    serviceLoadFailed: "The service could not be loaded.",
    serviceSaveFailed: "The service could not be saved.",
    serviceDeleteFailed: "%0% could not be deleted.",
    confirmDeleteHeadline: "Delete service",
    confirmDeleteContent: "Delete %0%? This cannot be undone.",
    confirmDelete: "Delete",
    confirmFailed: "The confirmation dialog could not be shown, so nothing was deleted.",
  },
};
