export default {
  ubookitSection: {
    label: "uBookIt",
  },
  ubookitResources: {
    label: "Resources",
    create: "Create resource",
    edit: "Edit",
    delete: "Delete",
    empty: "No resources yet. Create the first one to start taking bookings.",
    name: "Name",
    type: "Type",
    typeKey: "Type key",
    description: "Description",
    availability: "Availability",
    details: "Details",
    openingHours: "Opening hours",
    exceptions: "Exceptions",
    exception: "Exception",
    constraints: "Constraints",
    capabilities: "Capabilities",
    capabilityAdd: "Add capability",
    capabilityRemove: "Remove %0%",
    capabilityNone: "This resource has no capabilities.",
    capabilityHint: "Lower-case, hyphenated, e.g. cert-x. Choose one already in use, or enter a new one.",
    save: "Save",
    cancel: "Cancel",
    back: "Back to resources",
    newResource: "New resource",
    addWindow: "Add window",
    removeWindow: "Remove window",
    addException: "Add exception",
    removeException: "Remove exception",
    closedAllDay: "Closed all day",
    from: "From",
    to: "To",
    date: "Date",
    granularity: "Slot granularity (minutes)",
    minDuration: "Minimum duration (minutes)",
    maxDuration: "Maximum duration (minutes)",
    leadTime: "Minimum notice (minutes)",
    horizon: "Booking horizon (days)",
    previousPage: "Previous page",
    nextPage: "Next page",
    showing: "Showing %0%–%1% of %2%",
    actions: "Actions",
    tableLabel: "Bookable resources",
    pagingLabel: "Resource list pages",
    loadingList: "Loading resources",
    loadingResource: "Loading resource",
    errorSummary: "The resource could not be saved:",
    exceptionNeedsDate: "Each exception needs a date before saving.",
    dayMonday: "Monday",
    dayTuesday: "Tuesday",
    dayWednesday: "Wednesday",
    dayThursday: "Thursday",
    dayFriday: "Friday",
    daySaturday: "Saturday",
    daySunday: "Sunday",
    listLoadFailed: "The resource list could not be loaded.",
    resourceLoadFailed: "The resource could not be loaded.",
    resourceSaveFailed: "The resource could not be saved.",
    confirmDeleteHeadline: "Delete resource",
    confirmDeleteContent: "Delete %0%? This cannot be undone.",
    confirmDelete: "Delete",
    confirmFailed: "The confirmation dialog could not be shown, so nothing was deleted.",
  },
  ubookitServices: {
    label: "Services",
    create: "Create service",
    edit: "Edit",
    delete: "Delete",
    empty: "No services yet. Create one to offer a bookable service.",
    name: "Name",
    requirements: "Service Requirements",
    requirementsSummary: "Requires",
    requirementEntry: "%0% × %1%",
    requirementNone: "—",
    details: "Details",
    duration: "Duration",
    durationVariable: "Variable length",
    durationVariableHint:
      "The person booking chooses how long they need. Leave a limit empty to use whatever the booked resource allows — a resource's own limits always apply, so a booking can never be longer than the resource permits.",
    durationFixed: "Fixed length",
    durationMode: "Duration mode",
    durationMinutes: "Minutes",
    durationMin: "Shortest (minutes, optional)",
    durationMax: "Longest (minutes, optional)",
    durationRequired: "Enter a fixed length in minutes, or choose a variable length.",
    durationVariableSummary: "Variable",
    durationVariableRangeSummary: "Variable, %0%–%1% minutes",
    durationVariableMinSummary: "Variable, from %0% minutes",
    durationVariableMaxSummary: "Variable, up to %0% minutes",
    durationFixedSummary: "%0% minutes",
    resourceType: "Resource type",
    resourceTypeHint: "Choose a type already in use, or enter a new one.",
    requiredCapabilities: "Required capabilities",
    requiredCapabilitiesNone: "Any resource of this type.",
    requiredCapabilitiesHint: "Only resources with all of these can be booked for this service.",
    capabilityAdd: "Add capability",
    capabilityRemove: "Remove %0%",
    // Deliberately about capabilities, not about bookability: resources are
    // also excluded by duration, which this count does not check (design D8).
    requirementMatches: "%0% resources have these capabilities.",
    requirementMatchesOne: "1 resource has these capabilities.",
    requirementMatchesNone: "No resources have these capabilities.",
    save: "Save",
    cancel: "Cancel",
    back: "Back to services",
    newService: "New service",
    previousPage: "Previous page",
    nextPage: "Next page",
    showing: "Showing %0%–%1% of %2%",
    actions: "Actions",
    tableLabel: "Bookable services",
    pagingLabel: "Service list pages",
    loadingList: "Loading services",
    loadingService: "Loading service",
    errorSummary: "The service could not be saved:",
    listLoadFailed: "The service list could not be loaded.",
    serviceLoadFailed: "The service could not be loaded.",
    serviceSaveFailed: "The service could not be saved.",
    serviceDeleteFailed: "%0% could not be deleted.",
    confirmDeleteHeadline: "Delete service",
    confirmDeleteContent: "Delete %0%? This cannot be undone.",
    confirmDelete: "Delete",
    confirmFailed: "The confirmation dialog could not be shown, so nothing was deleted.",
  },
};
